#!/bin/sh
# UI Review bridge installer for macOS (Apple Silicon).
#
# Usage: ./install.sh --extension-id <32-letter Chrome extension id>
#
# Copies the standalone bridge into the user application-support directory, writes the
# Native Messaging launcher that pins the allowed extension origin, registers the host
# manifest for Google Chrome (stable) and runs a health check.
set -eu

EXTENSION_ID=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --extension-id)
      if [ "$#" -lt 2 ]; then
        echo "error: --extension-id needs a value" >&2
        exit 2
      fi
      EXTENSION_ID="$2"
      shift 2
      ;;
    -h|--help)
      echo "Usage: $0 --extension-id <32-letter Chrome extension id>"
      exit 0
      ;;
    *)
      echo "error: unknown option $1" >&2
      exit 2
      ;;
  esac
done

if [ "${#EXTENSION_ID}" -ne 32 ]; then
  echo "error: --extension-id must be the 32-letter id shown by chrome://extensions" >&2
  exit 2
fi
case "$EXTENSION_ID" in
  *[!a-p]*)
    echo "error: --extension-id may only contain the letters a-p" >&2
    exit 2
    ;;
esac

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
APP_DIR="$HOME/Library/Application Support/ui-review/bridge"
MANIFEST_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
EXECUTABLE="$APP_DIR/ui-review-bridge"
LAUNCHER="$APP_DIR/run-bridge.sh"
MANIFEST="$MANIFEST_DIR/com.dabik.ui_review_bridge.json"
ORIGIN="chrome-extension://$EXTENSION_ID/"

if [ ! -f "$HERE/ui-review-bridge" ]; then
  echo "error: ui-review-bridge is missing next to this installer" >&2
  exit 1
fi

mkdir -p "$APP_DIR" "$MANIFEST_DIR"
cp "$HERE/ui-review-bridge" "$EXECUTABLE"
chmod 755 "$EXECUTABLE"
# A downloaded artifact may carry the quarantine attribute; Chrome cannot launch it then.
xattr -d com.apple.quarantine "$EXECUTABLE" 2>/dev/null || true

cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Generated by the UI Review bridge installer. Do not edit.
export UI_REVIEW_BRIDGE_ALLOWED_ORIGINS="$ORIGIN"
exec "$EXECUTABLE" "\$@"
EOF
chmod 755 "$LAUNCHER"

cat > "$MANIFEST" <<EOF
{
  "name": "com.dabik.ui_review_bridge",
  "description": "UI Review local bridge: durable session artifact storage over Native Messaging.",
  "path": "$LAUNCHER",
  "type": "stdio",
  "allowed_origins": ["$ORIGIN"]
}
EOF

echo "UI Review bridge installed:"
echo "  executable: $EXECUTABLE"
echo "  launcher:   $LAUNCHER"
echo "  manifest:   $MANIFEST"
echo "Health check:"
"$EXECUTABLE" --health
echo "Reload the UI Review extension, then choose \"Check again\" in the side panel."
