# UI Review bridge installer for Windows x64.
#
# Usage: powershell -ExecutionPolicy Bypass -File .\install.ps1 -ExtensionId <32-letter id>
#
# Copies the standalone bridge under %APPDATA%, writes the Native Messaging launcher that
# pins the allowed extension origin, registers the host manifest for Google Chrome (stable)
# and runs a health check.
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ExtensionId
)

$ErrorActionPreference = "Stop"

if ($ExtensionId -notmatch '^[a-p]{32}$') {
    throw "ExtensionId must be the 32-letter id shown by chrome://extensions (letters a-p)."
}

$sourceExe = Join-Path $PSScriptRoot "ui-review-bridge.exe"
if (-not (Test-Path $sourceExe)) {
    throw "ui-review-bridge.exe is missing next to this installer."
}

$installDir = Join-Path $env:APPDATA "ui-review\bridge"
$executable = Join-Path $installDir "ui-review-bridge.exe"
$launcher = Join-Path $installDir "run-bridge.cmd"
$manifest = Join-Path $installDir "com.dabik.ui_review_bridge.json"
$origin = "chrome-extension://$ExtensionId/"
$registryKey = "HKCU:\Software\Google\Chrome\NativeMessagingHosts\com.dabik.ui_review_bridge"

New-Item -ItemType Directory -Force -Path $installDir | Out-Null
Copy-Item -Path $sourceExe -Destination $executable -Force

# The launcher pins the allowed origin; Chrome calls it with the caller origin as argument.
$launcherBody = @(
    "@echo off",
    "rem Generated by the UI Review bridge installer. Do not edit.",
    "set UI_REVIEW_BRIDGE_ALLOWED_ORIGINS=$origin",
    "`"$executable`" %*"
) -join "`r`n"
Set-Content -Path $launcher -Value $launcherBody -Encoding Ascii

$manifestDocument = [ordered]@{
    name            = "com.dabik.ui_review_bridge"
    description     = "UI Review local bridge: durable session artifact storage over Native Messaging."
    path            = $launcher
    type            = "stdio"
    allowed_origins = @($origin)
} | ConvertTo-Json
Set-Content -Path $manifest -Value $manifestDocument -Encoding UTF8

New-Item -Path $registryKey -Force | Out-Null
Set-ItemProperty -Path $registryKey -Name "(Default)" -Value $manifest

Write-Host "UI Review bridge installed:"
Write-Host "  executable: $executable"
Write-Host "  launcher:   $launcher"
Write-Host "  manifest:   $manifest"
Write-Host "  registry:   $registryKey"
Write-Host "Health check:"
& $executable --health
Write-Host 'Reload the UI Review extension, then choose "Check again" in the side panel.'
