/**
 * Release metadata for the standalone UI Review bridge. Pure module (no I/O, no Node APIs at
 * import time): `scripts/package-bridge.mjs` uses it to build the macOS and Windows
 * artifacts, and `tests/release/bridge-release.test.ts` uses it as the release check that
 * validates artifact naming, both host manifests and protocol compatibility.
 *
 * The extension id is not baked into the artifacts: the installers take it at install time
 * (the reviewer can read it from chrome://extensions), because an unpacked extension id
 * depends on the machine.
 */

export const BRIDGE_HOST_NAME = 'com.dabik.ui_review_bridge';
export const BRIDGE_HOST_DESCRIPTION =
  'UI Review local bridge: durable session artifact storage over Native Messaging.';

/** Node's single-executable sentinel and Mach-O segment name (postject injection). */
export const SEA_FUSE = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2';
export const SEA_BLOB_RESOURCE = 'NODE_SEA_BLOB';
export const SEA_MACHO_SEGMENT = 'NODE_SEA';

/** Chrome extension ids are 32 letters in the a-p range. */
export const EXTENSION_ID_PATTERN = /^[a-p]{32}$/;

/**
 * The two supported release targets. `installDirectory` and the host manifest directory use
 * `~` (macOS) and `%APPDATA%` (Windows) placeholders; the installers resolve them on the
 * target machine, so the plan stays deterministic and identical on every host.
 */
export const RELEASE_TARGETS = [
  {
    id: 'darwin-arm64',
    platform: 'darwin',
    arch: 'arm64',
    artifactName: 'ui-review-bridge-darwin-arm64',
    executableName: 'ui-review-bridge',
    launcherName: 'run-bridge.sh',
    installerName: 'install.sh',
    uninstallerName: 'uninstall.sh',
    installDirectory: '~/Library/Application Support/ui-review/bridge',
    hostManifest: {
      directory: '~/Library/Application Support/Google/Chrome/NativeMessagingHosts',
      fileName: `${BRIDGE_HOST_NAME}.json`,
    },
    registration: null,
  },
  {
    id: 'win-x64',
    platform: 'win32',
    arch: 'x64',
    artifactName: 'ui-review-bridge-win-x64',
    executableName: 'ui-review-bridge.exe',
    launcherName: 'run-bridge.cmd',
    installerName: 'install.ps1',
    uninstallerName: 'uninstall.ps1',
    installDirectory: '%APPDATA%\\ui-review\\bridge',
    hostManifest: {
      directory: '%APPDATA%\\ui-review\\bridge',
      fileName: `${BRIDGE_HOST_NAME}.json`,
    },
    registration: {
      kind: 'windows-registry',
      key: `HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts\\${BRIDGE_HOST_NAME}`,
    },
  },
];

export function findReleaseTarget(id) {
  return RELEASE_TARGETS.find((target) => target.id === id) ?? null;
}

export function isValidExtensionId(value) {
  return typeof value === 'string' && EXTENSION_ID_PATTERN.test(value);
}

function joinTargetPath(target, name) {
  const separator = target.platform === 'win32' ? '\\' : '/';
  return `${target.installDirectory}${separator}${name}`;
}

/** The launcher path exactly as the installer will write it on the target machine. */
export function launcherPathFor(target) {
  return joinTargetPath(target, target.launcherName);
}

export function executablePathFor(target, directory = target.installDirectory) {
  const separator = target.platform === 'win32' ? '\\' : '/';
  return `${directory}${separator}${target.executableName}`;
}

/**
 * Native Messaging host manifest for one target and one extension id. Chrome requires
 * `name`, `path`, `type: "stdio"` and `allowed_origins`; the path points at the launcher
 * because the allowlist env var is set there, not in the manifest.
 */
export function buildHostManifest(target, { extensionId, launcherPath }) {
  if (!isValidExtensionId(extensionId)) {
    throw new Error(`"${extensionId}" is not a Chrome extension id (32 letters a-p).`);
  }
  return {
    name: BRIDGE_HOST_NAME,
    description: BRIDGE_HOST_DESCRIPTION,
    path: launcherPath,
    type: 'stdio',
    allowed_origins: [`chrome-extension://${extensionId}/`],
  };
}

/** Launcher body shared with the installers' documentation; the installers write it themselves. */
export function buildLauncher(target, { origin, executablePath }) {
  if (target.platform === 'win32') {
    return [
      '@echo off',
      'rem Generated by the UI Review bridge installer. Do not edit.',
      `set UI_REVIEW_BRIDGE_ALLOWED_ORIGINS=${origin}`,
      `"${executablePath}" %*`,
      '',
    ].join('\r\n');
  }
  return [
    '#!/bin/sh',
    '# Generated by the UI Review bridge installer. Do not edit.',
    `export UI_REVIEW_BRIDGE_ALLOWED_ORIGINS="${origin}"`,
    `exec "${executablePath}" "$@"`,
    '',
  ].join('\n');
}

/**
 * Deterministic release plan: what the packaged artifacts are, where they install and which
 * host manifest they register. `extensionId` is optional; without it the plan only describes
 * the shapes (no manifest document is generated).
 */
export function buildReleasePlan({ version, protocolVersion, nodeVersion, extensionId = null }) {
  return {
    version,
    protocolVersion,
    nodeVersion,
    hostName: BRIDGE_HOST_NAME,
    targets: RELEASE_TARGETS.map((target) => ({
      id: target.id,
      platform: target.platform,
      arch: target.arch,
      artifactName: target.artifactName,
      executableName: target.executableName,
      launcherName: target.launcherName,
      installerName: target.installerName,
      uninstallerName: target.uninstallerName,
      installDirectory: target.installDirectory,
      hostManifest: {
        directory: target.hostManifest.directory,
        fileName: target.hostManifest.fileName,
        document:
          extensionId === null
            ? null
            : buildHostManifest(target, {
                extensionId,
                launcherPath: launcherPathFor(target),
              }),
      },
      registration: target.registration,
    })),
  };
}
